# Generated by Django 6.0.4 on 2026-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hostel_fee',
            field=models.IntegerField(default=5000),
        ),
    ]
